Adding transient storage check in Invariant
Certora/Documentation pull request #268
Opened 2024-06-21 10:14 UTC by johspaeth

This PR adds a description of the new feature for checking transient storage as part of an invariant check.

2024-06-23 09:53 UTC, urikirsh requested changes
See comments for questions

2024-06-23 09:53 UTC, urikirsh commented on docs/cvl/invariants.md
> +With the introduction of transient storage in solidity ([EIP-1153](https://eips.ethereum.org/EIPS/eip-1153),
```suggestion
With the introduction of transient storage in Solidity ([EIP-1153](https://eips.ethereum.org/EIPS/eip-1153),
```

2024-06-23 09:53 UTC, urikirsh commented on docs/cvl/invariants.md
> +solidity contracts can now use a `tload` or `tstore` instruction to perform load and stores on transient storage.
```suggestion
Solidity contracts can now use a `tload` or `tstore` instruction to perform `load` and `store` on transient storage.
```

2024-06-23 09:53 UTC, urikirsh commented on docs/cvl/invariants.md
> +A storage that will be reset after the transaction has terminated.
```suggestion
The transient storage will be reset after the transaction has terminated. 
```
I believe this was the intention? This sentence was not clear

2024-06-23 09:53 UTC, urikirsh commented on docs/cvl/invariants.md
> +The Prover will automatically detect the usage of `tload` and `tstore` in the solidity contract
```suggestion
The Prover will automatically detect the usage of `tload` and `tstore` in the Solidity contract
```

2024-06-23 09:53 UTC, urikirsh commented on docs/cvl/invariants.md
> +The Prover will automatically detect the usage of `tload` and `tstore` in the solidity contract
which contract?

2024-06-24 07:23 UTC, johspaeth commented on docs/cvl/invariants.md
> +The Prover will automatically detect the usage of `tload` and `tstore` in the solidity contract
Has been clarified.

2024-06-24 13:31 UTC, urikirsh approved these changes
lgtm

2024-07-25 08:29 UTC, merged